### ISSUE TITLE
proxy handling

### ISSUE THREAD

**Issue by maku** [Omertron/api-thetvdb#14]
It would be nice to be able to work with the API also behind a proxy.

In the used lib (HttpComponentes) the java proxy system vars (-DproxySet=true -DproxyHost=myproxy -DproxyPort=8080)  don't work. So you would have to use the proxy via the HttpComponents API

```

HttpHost target = new HttpHost("httpbin.org", 443, "https");
HttpHost proxy = new HttpHost("127.0.0.1", 8080, "http");

RequestConfig config = RequestConfig.custom().setProxy(proxy).build();
HttpGet request = new HttpGet("/");
request.setConfig(config);

CloseableHttpResponse response = httpclient.execute(target, request);

````

**Comment by maku** [comment]
This code for DOMHelper.requestWebPage should provide proxy handling:

```
 if("true".equals(System.getProperty("proxySet"))) {
	String proxyHost = System.getProperty("proxyHost");
	if(proxyHost!=null) {
		String proxyPort = System.getProperty("proxyPort");
		int port = proxyPort!=null?Integer.valueOf(proxyPort):80;
		HttpHost proxy = new HttpHost(proxyHost, port);
		RequestConfig config = RequestConfig.custom().setProxy(proxy).build();
		httpGet.setConfig(config);
	}
}

```

**Comment by Omertron** [comment]
Sorry for taking so long to reply.

Basically if you want to add proxy support you can do this through building a HttpClient via the SimpleHttpClientBuilder method.

        HttpClient hc = new SimpleHttpClientBuilder()
                .setProxyHost("HOST")
                .setProxyPort(PORT)
                .setProxyUsername("USERNAME")
                .setProxyPassword("PASSWORD")
                .build();

**Comment by maku** [comment]
I know how to add proxy support. e.g. like I posted on 25th Sep (I cloned api-thevdb and added the code). This would be a way how api-thetvdb can add proxy handling in an "expected" way

**Comment by Omertron** [comment]
I used to have code similar to that in all my APIs, but some users wanted a finer grain control over whether the proxy should be used or not for different APIs.

Therefore I found it easier to leave the choice to the user rather than force the proxy control on or off.
