### ISSUE TITLE
NullPointerException when searching

### ISSUE THREAD

**Issue by GideonLeGrange** [Omertron/api-thetvdb#19]
I'm experiencing a `NullPointerException` in certain instances when calling `searchSeries()`. I'm not exactly sure why this is, but I suspect that the problem may be todo with `getValidWebpage()` returning null and `getEventDocFromUrl()` not checking it. 

Here is code to reproduce the error:

```java 
import com.omertron.thetvdbapi.TheTVDBApi;
import com.omertron.thetvdbapi.model.Episode;
import com.omertron.thetvdbapi.model.Series;
import java.util.List;

public class NullPointerExample {
    
    private static final String API_KEY = "YOUR API KEY HERE";
    
    public static void main(String...args) throws Exception { 
        TheTVDBApi tvDB = new TheTVDBApi(API_KEY);
        List<Series> results = tvDB.searchSeries("Fairly odd parents", "en");
        for (Series series : results) {
            System.out.println(series.getId() + " " + series.getSeriesName());
            List<Episode> episodes = tvDB.getAllEpisodes(series.getId(), "en");
            for (Episode ep : episodes) {
                System.out.println(ep.getEpisodeNumber() + " " + ep.getEpisodeName());
            }
        }
        
    }

}
```

Here is the stack trace from the error:

```
Exception in thread "main" java.lang.NullPointerException
	at com.omertron.thetvdbapi.tools.DOMHelper.getEventDocFromUrl(DOMHelper.java:122)
	at com.omertron.thetvdbapi.tools.TvdbParser.getSeriesList(TvdbParser.java:256)
	at com.omertron.thetvdbapi.TheTVDBApi.searchSeries(TheTVDBApi.java:362)
	at NullPointerExample.main(NullPointerExample.java:13)
````

**Comment by GideonLeGrange** [comment]
I see I may have reported the same problem as #17. I'm testing against current `master` to see if it's better.

**Comment by GideonLeGrange** [comment]
Seems to work correctly in 1.9-SNAPSHOT, so this is a duplicate of #17. Time for a 1.9 release to Maven Central (hint hint) 😀

**Comment by Omertron** [comment]
Thank you, I will release today/tomorrow

**Comment by Omertron** [comment]
And released

**Comment by GideonLeGrange** [comment]
Awesome, thank you. Did you push it to Central? They're only showing up to 1.8 currently. 

![screen shot 2016-08-31 at 18 32 00](https://cloud.githubusercontent.com/assets/1131028/18137610/5223caaa-6fa9-11e6-82b5-53f4bf77f21f.png)

**Comment by Omertron** [comment]
Dang! Forgot to do that step. It's done now.
