### ISSUE TITLE
NoSuchMethodError when calling TheTVDBApi.getAbsoluteEpisode

### ISSUE THREAD

**Issue by TheRootDeveloper01** [Omertron/api-thetvdb#9]
When calling TheTVDBApi.getAbsoluteEpisode I get this exception : 
<code>java.lang.NoSuchMethodError: No interface method  requestContent(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String; in class Lorg/yamj/api/common/http/CommonHttpClient; or its super classes (declaration of 'org.yamj.api.common.http.CommonHttpClient' </code>
I already have implemented api-commons-1.3 as library from the maven repository.
Any suggestions?
Thanks for your help

**Comment by Omertron** [comment]
Please try with api-commons-1.4-SNAPSHOT 

We have been updating the libraries to use HttpClient 4.4 and this may have causes some issues.

I will be releasing updated versions that work together

**Comment by Omertron** [comment]
The latest snapshot of the API should now work

**Comment by TheRootDeveloper01** [comment]
Thanks I'll try later.

**Comment by TheRootDeveloper01** [comment]
I added the new api-commons 1,4 but the same error is caught.
In my project there are these library:
-api-common-1.4
-commons-lang3-3.3.2
-log4j-1.2.17
-slf4j-api-1.7.2
-thetvdbapi-1.7

Anything wrong?
Thank you for your time.

**Comment by Omertron** [comment]
Right now you need to use the SNAPSHOT of thetvdbapi.

If you don't want to use the snapshot, make sure you specify api-common-1.2 and that should work together

**Comment by TheRootDeveloper01** [comment]
I'm sorry to disturb you again, but I'm a bit confused. I added the snapshot of your api but then I need to add httpclient and httpcore jars. But they conflict eachother so I added in the grandle the packaging options to avoid this conflict. When I run and create a new istance of TheTVDBApi I get this : 
<code>No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier</code>
Any suggestions? I will now try with the api-common-1.2 and the previous api relase.
Thank you very much.

**Comment by Omertron** [comment]
No worries, I know there were some issues when transitioning.

thetvdbapi 1.7 and api-common 1,2 will work together (using httpclient 3.6), 1.8-SNAPSHOT and api-common 1,4 will work together (using httpclient 4.4)

**Comment by TheRootDeveloper01** [comment]
I downloaded api-common 1.2 but I can't find any httpclient 3.6, even on the apache.org archive (http://archive.apache.org/dist/httpcomponents) it's not present.

**Comment by TheRootDeveloper01** [comment]
Just resolved, it was a library conflict made by grandle in androidstudio.

**Comment by Omertron** [comment]
Ok, great, thanks for letting me know.
